6 - Create footer component
gdg-minsk/gdg-minsk-website pull request #1
Opened 2019-10-10 21:31 UTC by smirnovvy

2019-10-11 06:59 UTC, IlyaZaprutski commented on src/components/footer.js
> +                    GDG Minsk {new Date().getFullYear()}
можно получать название из конфига использую useStaticQuery

2019-10-11 06:59 UTC, IlyaZaprutski commented on src/components/footer.js
> +    root: {
необходимо прижать футер

2019-10-11 06:59 UTC, IlyaZaprutski commented on src/components/layout.js
>  import Container from '@material-ui/core/Container';
следует добавить компонент (https://material-ui.com/components/css-baseline/) для нормализации стилей

2019-10-12 18:03 UTC, smirnovvy commented on src/components/footer.js
> +                    GDG Minsk {new Date().getFullYear()}
Done

2019-10-12 18:03 UTC, smirnovvy commented on src/components/footer.js
> +    root: {
Done

2019-10-12 18:37 UTC, IlyaZaprutski requested changes

2019-10-12 18:37 UTC, IlyaZaprutski commented on src/components/shared/layout/footer/footer.jsx
> +import CssBaseline from '@material-ui/core/CssBaseline';
CssBaseline не используется

2019-10-12 18:37 UTC, IlyaZaprutski commented on src/components/shared/layout/layout.jsx
> +        <div className={classes.root}>
используй компонент box

2019-10-12 18:41 UTC, smirnovvy commented on src/components/shared/layout/footer/footer.jsx
> +import CssBaseline from '@material-ui/core/CssBaseline';
ремувнул

2019-10-12 18:41 UTC, smirnovvy commented on src/components/shared/layout/layout.jsx
> +        <div className={classes.root}>
done

2019-10-12 18:43 UTC, IlyaZaprutski requested changes

2019-10-12 18:43 UTC, IlyaZaprutski commented on src/components/shared/layout/footer/footer.jsx
> +    <>
можно убрать фрмагмент тк футер единственная нода

2019-10-12 18:47 UTC, smirnovvy commented on src/components/shared/layout/footer/footer.jsx
> +    <>
да, не знаю, почему решил добавить :)

2019-10-12 19:03 UTC, IlyaZaprutski approved these changes

2019-10-12 19:03 UTC, merged